services:
  database:
    image: postgres:15
    container_name: shortify-db
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${MY_PASSWORD}
      POSTGRES_DB: ${MY_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network

  backend:
    image: frankxhunter/shortify-backend
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    container_name: shortify-backend
    env_file:
      - .env
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${MY_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MY_USER}
      SPRING_DATASOURCE_PASSWORD: ${MY_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
    expose:
      - "8080"
    networks:
      - shortener-network

  nginx:
    image: nginx:latest
    container_name: shortify-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shortener-network

volumes:
  postgres_data:
  certs:

networks:
  shortener-network: