spring.application.name=shortify
# Data base configuration
spring.datasource.url=${MY_DATABASE_URL}
spring.datasource.username=${MY_USER}
spring.datasource.password=${MY_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Security
application.security.jwt.secret=${JWT_SECRET}
application.security.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:300000}
application.security.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:2592000000}
# Mail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# IP info
ipinfo.token=${IPINFO_TOKEN}
